Function
atharvaskadam/golang pull request #20
Opened 2022-11-03 09:16 UTC by atharvaskadam

@aasisodiya Check This Please

2022-11-04 19:56 UTC, aasisodiya requested changes

2022-11-04 19:56 UTC, aasisodiya commented on readwrite/main.go
> +
Why do you have this code in this PR?

2022-11-04 19:56 UTC, aasisodiya commented on function/main.go
> +}
All is good, but always keep your returned parameters with name, and I hope you know the purpose of camelCase and TitleCase in Golang Function Naming?????

2022-11-09 13:52 UTC, atharvaskadam commented
@aasisodiya Addressed review comments

2022-11-09 13:53 UTC, aasisodiya approved these changes

2022-11-09 13:53 UTC, merged